### ISSUE TITLE
Does not work on Content

### ISSUE THREAD

**Issue by lockieluke** [Quintschaf/SwiftUI-Inspect#1]
Attempting to inspect a `ScrollView`:
<img width="1096" alt="image" src="https://user-images.githubusercontent.com/25424409/227793645-d544392a-97c9-4e6d-9280-cd8e75a926ec.png">

Expected behaviour as in Introspect:
<img width="587" alt="image" src="https://user-images.githubusercontent.com/25424409/227793692-187cd96a-41da-4628-9273-6e5ad06cd8d9.png">

**Comment by JannThomas** [comment]
Inspects public API heavily embraces Swifts strong type system. You can only call inspect on the SwiftUI type that corresponds to the searched-for UIKit or AppKit type. For example, on iOS, you call inspect() on a SwiftUI TextField and get a UITextField. You cannot call inspect() to retrieve a UITextField on any other SwiftUI type, not even on a modified TextField. This does not apply to UITableViewCell resp. UICollectionViewCell, which do not have a corresponding SwiftUI type.

**Comment by JannThomas** [comment]
This should solve your problem 😊
```swift
extension ScrollView {
  func transparentScrollbars() -> some View {
    self.inspect { scrollView in
      scrollView.autohidesScrollers = true
      scrollView.scrollerStyle = .overlay
    }
  }
}
```
